### ISSUE TITLE
olego versions

### ISSUE THREAD

**Issue by ramiromagno** [chaolinzhanglab/olego#3]
Hi,

in the documentation here: https://zhanglab.c2b2.columbia.edu/index.php/OLego_Documentation

I see that versions 1.1.6 and 1.1.7 exist, but such versions are not listed in the GitHub [README ](https://github.com/chaolinzhanglab/olego/blob/master/README). When I `git clone` and run `make`, the olego returns version  1.1.5:

```bash
OLego: version 1.1.5
Compiled at 14:52:36, Sep  8 2020
Usage:   olego [options] <prefix> <in.fastx>
```

So does this mean that versions 1.1.6 and 1.1.7 are not included in the code base of GitHub repository?

**Comment by chaolinzhanglab** [comment]
The most recent version of the code is 1.1.7.  Somehow the version number was not updated in the code, but fixed now if you like to pull the code again.  Apologies for that.

Chaolin

**Comment by ramiromagno** [comment]
That's alright! I can confirm that the version prints now 1.1.7.

```bash
OLego: version 1.1.7
Compiled at 10:07:14, Sep  9 2020
Usage:   olego [options] <prefix> <in.fastx>
```
