### ISSUE TITLE
What files to install?

### ISSUE THREAD

**Issue by ramiromagno** [chaolinzhanglab/olego#4]
To build olego I have `git clone` the repository, and ran `make`.

Now, besides the two executables `olego` and `olegoindex`, should I also copy the Perl scripts included in the build folder, namely:

- bed2junc.pl
- mergePEsam.pl
- qualfa2fq.pl
- sam2bed.pl
- sam2junctionread.pl
- solid2fastq.pl
- xa2multi.pl

I am installing this on a Ubuntu 20.04, and I am planning on making it available to all users.

So my plan is to place both the executables and the Perl scripts in `/opt/olego/`. Do these programs depend on other files in the build directory that need copying too?

Thank you.

**Comment by chaolinzhanglab** [comment]
Hi, 

OLego does not depends on the perl scripts, but they are used for post-processing steps.  You can find documents here: 

https://zhanglab.c2b2.columbia.edu/index.php/OLego_Documentation <https://zhanglab.c2b2.columbia.edu/index.php/OLego_Documentation>

and here:

https://zhanglab.c2b2.columbia.edu/index.php/Quantas_Documentation <https://zhanglab.c2b2.columbia.edu/index.php/Quantas_Documentation>

Chaolin

**Comment by ramiromagno** [comment]
and the Perl scripts are self-contained? i.e., they do not depend any modules, do they?

**Comment by zhangchaolin** [comment]
Yes, they should be self-contained.
