### ISSUE TITLE
Exon junction database human (hg19)

### ISSUE THREAD

**Issue by MercedesBentata** [chaolinzhanglab/olego#5]
Hello,
I don't manage to download the human junction file (human (hg19) (356,777 unique junctions)) you provide in the documentation web.
Maybe the link is not correct?
Thanks in advance!

**Comment by zhangchaolin** [comment]
Hi,

The link is somehow broken.  Will fix ASAP.

Chaolin

**Comment by zhangchaolin** [comment]
The link should be back now.

Thanks for letting us know.

Chaolin

**Comment by MercedesBentata** [comment]
Thanks!
It is indeed fixed.
