### ISSUE TITLE
mergePEsam.pl

### ISSUE THREAD

**Issue by MercedesBentata** [chaolinzhanglab/olego#6]
After running OLego, I am trying to merge my 2 sam files but I got this error:
"Wrong XA format"
How could I solve the problem?
Thanks in advance!

**Comment by jiewuphilips** [comment]
> After running OLego, I am trying to merge my 2 sam files but I got this error:
> "Wrong XA format"
> How could I solve the problem?
> Thanks in advance!

@MercedesBentata  Could you please provide some files (with a few rows) that can be used to debugging? Thanks!

**Comment by MercedesBentata** [comment]
This an example of a problematic row:

UNC13-SN749:327:C36RUACXX:4:1101:1047:19074     16      NC_000017.11    38404346        0       48M     *       0       0       GTCGCTCAGTTTCTTCCTGTTTCCCTTCCTGTCCTCTCCNCACCTGCT        F@;B3GFBGD??;D8B03HCFFDEDGFDIHGFEE??<22#B2AD;??;XT:A:R   NM:i:1  XS:A:.  X0:i:2  X1:i:0  XM:i:1  XO:i:0  XG:i:0  MD:Z:39A8       XA:Z:NT_187614.1,-2439665,48M,1,.;

**Comment by zhangchaolin** [comment]
Hi,

It looks like your reference genome is not typical (chr1, …).

Chaolin

**Comment by MercedesBentata** [comment]
Fistly, I ran olegoindex on the Reference Genome Sequence GRCh38 fasta file provided in https://www.ncbi.nlm.nih.gov/genome/guide/human/

Is this file not suitable?

**Comment by zhangchaolin** [comment]
We recommend that you keep only the chromosome files and remove all the contigs, haplotype, random fragments, etc.

**Comment by MercedesBentata** [comment]
Okay, thanks for the answer!
I will try doing that.

**Comment by MercedesBentata** [comment]
I changed the genome reference file accordingly and the problem got solved. Thanks!
